on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Deploy Containers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fedora_version: ["32", "33", "34", "35", "36", "37", "38"]
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-${{ matrix.fedora_version }}

      - uses: docker/build-push-action@v2
        with:
          build-args: fedora_version=${{ matrix.fedora_version }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
