on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Deploy Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fedora_version: ["32", "33", "34", "35", "36", "37", "38", "39"]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}-${{ matrix.fedora_version }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            fedora_version=${{ matrix.fedora_version }}
          pull: true
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: |
            ghcr.io/${{ github.repository }}-${{ matrix.fedora_version }}:main
            ${{ steps.docker_meta.outputs.tags }}
          cache-to: type=inline
